# I am a workflow that demonstrates how to output the different context objects

name: test case

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  VAR1: foo
  var2: bar

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

#  job1:
#    runs-on: ubuntu-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#    
#      - run: |
#          echo ${{env.VAR1}}
#          echo ${{env.var1}}

  job2:
    runs-on: ubuntu-latest
    
    steps:
    
      - run: |
          echo ${{env.VAR1}}
          echo ${{env.var2}}
          echo ${{env.VAR3}}
          echo ${{env.var3}}
        env: 
          VAR3: mystepvar3
          var3: noway
    
